version: '0.0.1'

services:
  categories-products-crud-assignment:
    container_name: crud-assignment
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://crud-assignment-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  postgres:
    image: postgres:latest
    container_name: crud-assignment-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"